import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import math
# import itertools
from itertools import combinations
import time as tm

# Generate Cyclic Cayley Graph

def cyclic_cayley(n, H):
    """ Creates adjacency matrix for Cayley graph for cyclic group C_n generated by H. C_n is additive i.e. elements are 0,...,n-1.
    
    Args:
        n: number of nodes
        H: subset of C_n that generates edges for the Cayley graph
    
    Returns:
        adj_matrix: adjacency matrix of the Cayley graph
    
    """
    adj_matrix = np.zeros((n,n))
    for i in range(n):
        for h in H:
            j = (i+h)%n
            adj_matrix[i,j] = 1
    return adj_matrix


if __name__ == '__main__':
    # Example of drawing Cayley graph with node labels and colors
    n = 7
    H = [2,3]
    g = cyclic_cayley(n, H)
    print(f"adjacency matrix = {g}")
    print("")

    G = nx.from_numpy_array(g, create_using=nx.DiGraph)
#     nx.draw(G, with_labels = True, node_color = colors)
    nx.draw_circular(G, with_labels = True)
    plt.show()

# Compute orbits of a cyclic Cayley graph

def get_orbits(n, s):
    """ Partitions all possible starting sets into their equivalent orbits
    
    Args:
        n: number of nodes in cyclic Cayley graph
        s: cardinality of starting sets
    
    Returns:
        orbits: list whose elements are lists of starting sets which lie in the same orbit
    
    """
    orbits = []
    for state in list(combinations(range(n), s)):
        if len(orbits) == 0:
            new_orbit = [set(state)]
#            fix a j in Cn to add by
            for j in range(1, n):
#                add each node in initial starting set by j
                new_state = []
                for i in state:
                    k = (i+j)%n
                    new_state.append(k)
                if not set(new_state) in new_orbit:
                    new_orbit.append(set(new_state))
            orbits.append(new_orbit)
        else:
#            if the current state is already in another orbit, move to the next possible starting state    
            for orbit in orbits:
                if set(state) in orbit:
                    break
#            if the starting state was not in any previous orbits, generate that state's orbit and append to the list of orbits
            else:
                new_orbit = [set(state)]
#                fix a j in Cn to add by
                for j in range(1,n):
#                    add each state by j
                    new_state = []
                    for i in state:
                        k = (i+j)%n
                        new_state.append(k)
                    if not set(new_state) in new_orbit:
                        new_orbit.append(set(new_state))
                orbits.append(new_orbit)
    return orbits

if __name__ == '__main__':
    n = 7
    H = [2,3]
    g = cyclic_cayley(n, H)

    # number of initially active nodes
    s = 2
    
    all_orbits = get_orbits(n, s)
    print(f"Number of distinct orbits = {len(all_orbits)}")
    for i, orbit in enumerate(all_orbits):
        print(f"orbit {i} = {orbit}")
    
    print("")

def active_neighbors(node, state, g):
    """ Calculates number of activated neighbors that input node has
    
    Args:
        node: current node
        state: current state of the graph
        g: adjacency matrix for the graph
        
    Returns:
        val: number of active neighbors that node has
        
    """
    n = len(state)
    val = 0
    for i in range(n):
        val += state[i]*g.transpose()[node][i]
    return val

def update(state, g, t):
    """ Updates network
    
    Args:
        state: current state of network
        g: adjacency matrix
        t: threshold for activation
    
    Returns:
        new_state: the next state that the network will be in
    
    """
    new_state = state.copy()
    s = len(state)
    for i in range(s):
        a_num = 0
        if state[i] == 0:
            a_num = active_neighbors(i, state, g)
            if a_num >= t:
                new_state[i] = 1
        else:
            new_state[i] = 1
    return new_state

def cayley_times(g, t, s):
    """ Calculate average speeds over starting sets of cardinality s, min non-zero speeds, max speeds, and activation probability for graph g and threshold t
    
    Args:
        g: adjacency matrix
        t: threshold for activation
        I: number of initially active nodes
    
    Returns:
        avg_speeds: array of average speeds
        min_speeds: array of minimum non-zero speeds
        max_speeds: array of maximum speeds
        sync_probability: array of synchronization probabilities
        avg_steps: average number of steps until full activation
    """
    n = len(g)
    orbits = get_orbits(n, s)
    
    # Initialize array for keeping track of slowest and fastest synchronization times (greater than 0)
    min_speed = 0
    max_speed = 0

    # Initialize array for sum of speeds
    sum_speed = 0
    sum_steps = 0

    # Initialize array for keeping track of number of times the network synchronized
    num_sync = 0
    
    for orbit in orbits:
        state = np.zeros(n)
        for i in orbit[0]:
#             print(i, orbit[0])
            state[int(i)] = 1
        next_state = update(state, g, t)

    #     Initialize variable for keeping track of time until synchronization was reached
        sync_time = 0
        while np.any(state != next_state):
    #         Update the current state to the next state
            state = next_state.copy()

    #         Plot the current state of the graph
    #         colors = state_colors(state)
    #         G = nx.from_numpy_array(np.matrix(g))
    #         nx.draw_circular(G, with_labels = True, node_color = colors)
    #         plt.show()
            next_state = update(state, g, t)
            sync_time += 1

    #     Calculate the sum of speeds
    #     We only add the speed if the network synchronized. Otherwise we "add" 0.
        if sync_time != 0 and sum(state) == n:
            sum_speed += (1/sync_time)*len(orbit)
            sum_steps += sync_time*len(orbit)
            num_sync += 1*len(orbit)
    #         Update max_speed if a faster speed occured
            if 1/sync_time > max_speed:
                max_speed = 1/sync_time
    #         If set the min_speed to be the speed of the first graph that synchronized
            if min_speed == 0:
                min_speed = 1/sync_time
    #         Update min_speed if a slower speed occured
            elif 1/sync_time < min_speed:
                min_speed = 1/sync_time
                
    # Calculate average speed until synchronization
    avg_speed = 0
    avg_steps = 0
    sync_probability = 0
    num_combinations = math.comb(n, s)
    if sum_speed != 0:
        avg_speed = sum_speed/num_combinations
        avg_steps = sum_steps/num_combinations
    sync_probability = num_sync/num_combinations
    
    return avg_speed, min_speed, max_speed, sync_probability, avg_steps

def get_H_sets(n, h):
    """ Partitions all edge generating sets into sets that produce isomorphic graphs
    
    Args:
        n: number of nodes in the graph
        h: cardinality of edge generating sets
        
    Returns:
        H_sets: 
    
    """
    H_sets = []
    for H in list(combinations(range(1,n), h)):
        if len(H_sets) == 0:
            H_sets.append([H])
        else:
            appended = False
            for i in range(len(H_sets)):
                g1 = cyclic_cayley(n, H_sets[i][0])
                G1 = nx.from_numpy_array(g1, create_using=nx.DiGraph)
#                 nx.draw_circular(G1, with_labels = True)
#                 plt.show()

                g2 = cyclic_cayley(n, H)
                G2 = nx.from_numpy_array(g2, create_using=nx.DiGraph)
#                 nx.draw_circular(G2, with_labels = True)
#                 plt.show()

                if nx.is_isomorphic(G1, G2):
                    H_sets[i].append(H)
                    appended = True
                    break
            if not appended:
#                 print(H)
                H_sets.append([H])
                
#             print(H_sets)
                
    return H_sets

if __name__ == '__main__':
    n = 7
    h = 2
    
    H_sets = get_H_sets(n, h)
    
    for i, H_set in enumerate(H_sets):
        print(f"graph {i} is generated by {H_set}")

    print("")




